/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as InvitationIdRouteImport } from './routes/invitation.$id'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellImportRouteImport } from './routes/_shell/import'
import { Route as ShellTreeIdRouteImport } from './routes/_shell/tree.$id'
import { Route as ShellPersonIdRouteImport } from './routes/_shell/person.$id'
import { Route as ShellTreeIdSettingsRouteImport } from './routes/_shell/tree.$id_.settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImportRoute = ShellImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTreeIdRoute = ShellTreeIdRouteImport.update({
  id: '/tree/$id',
  path: '/tree/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPersonIdRoute = ShellPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTreeIdSettingsRoute = ShellTreeIdSettingsRouteImport.update({
  id: '/tree/$id_/settings',
  path: '/tree/$id/settings',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/import': typeof ShellImportRoute
  '/profile': typeof ShellProfileRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/person/$id': typeof ShellPersonIdRoute
  '/tree/$id': typeof ShellTreeIdRoute
  '/tree/$id/settings': typeof ShellTreeIdSettingsRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/import': typeof ShellImportRoute
  '/profile': typeof ShellProfileRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/': typeof ShellIndexRoute
  '/person/$id': typeof ShellPersonIdRoute
  '/tree/$id': typeof ShellTreeIdRoute
  '/tree/$id/settings': typeof ShellTreeIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_shell/import': typeof ShellImportRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/person/$id': typeof ShellPersonIdRoute
  '/_shell/tree/$id': typeof ShellTreeIdRoute
  '/_shell/tree/$id_/settings': typeof ShellTreeIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/import'
    | '/profile'
    | '/invitation/$id'
    | '/person/$id'
    | '/tree/$id'
    | '/tree/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/import'
    | '/profile'
    | '/invitation/$id'
    | '/'
    | '/person/$id'
    | '/tree/$id'
    | '/tree/$id/settings'
  id:
    | '__root__'
    | '/_shell'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_shell/import'
    | '/_shell/profile'
    | '/invitation/$id'
    | '/_shell/'
    | '/_shell/person/$id'
    | '/_shell/tree/$id'
    | '/_shell/tree/$id_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InvitationIdRoute: typeof InvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/import': {
      id: '/_shell/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ShellImportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tree/$id': {
      id: '/_shell/tree/$id'
      path: '/tree/$id'
      fullPath: '/tree/$id'
      preLoaderRoute: typeof ShellTreeIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/person/$id': {
      id: '/_shell/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof ShellPersonIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tree/$id_/settings': {
      id: '/_shell/tree/$id_/settings'
      path: '/tree/$id/settings'
      fullPath: '/tree/$id/settings'
      preLoaderRoute: typeof ShellTreeIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellImportRoute: typeof ShellImportRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellPersonIdRoute: typeof ShellPersonIdRoute
  ShellTreeIdRoute: typeof ShellTreeIdRoute
  ShellTreeIdSettingsRoute: typeof ShellTreeIdSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellImportRoute: ShellImportRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellPersonIdRoute: ShellPersonIdRoute,
  ShellTreeIdRoute: ShellTreeIdRoute,
  ShellTreeIdSettingsRoute: ShellTreeIdSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InvitationIdRoute: InvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
